{{- /*
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
*/ -}}

{{- if .Values.defaultVaultConnection.enabled }}
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultConnection
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    component: controller-manager
    app.kubernetes.io/component: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  address: {{ .Values.defaultVaultConnection.address }}
  skipTLSVerify: {{ .Values.defaultVaultConnection.skipTLSVerify }}
  {{- if .Values.defaultVaultConnection.caCertSecret }}
  caCertSecretRef: {{ .Values.defaultVaultConnection.caCertSecret }}
  {{- end }}
  {{- if .Values.defaultVaultConnection.tlsServerName }}
  tlsServerName: {{ .Values.defaultVaultConnection.tlsServerName }}
  {{- end }}
  {{- if .Values.defaultVaultConnection.headers }}
  headers:
    {{ tpl .Values.defaultVaultConnection.headers . | trim }}
  {{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-pre-delete-vault-connection-cr
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: testing-stuff
    spec:
      serviceAccountName: {{ include "chart.fullname" . }}-controller-manager
      containers:
      - name: test
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - {{ printf "kubectl delete vaultconnections.secrets.hashicorp.com -n %s default" .Release.Namespace }}
      restartPolicy: Never
{{- end }}
