{{- /*
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
*/ -}}

{{- if .Values.defaultAuthMethod.enabled }}
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuth
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    component: controller-manager
    app.kubernetes.io/component: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.defaultAuthMethod.vaultConnectionRef }}
  vaultConnectionRef: {{ .Values.defaultAuthMethod.vaultConnectionRef }}
  {{- end }}
  namespace: {{ .Values.defaultAuthMethod.namespace }}
  method: {{ .Values.defaultAuthMethod.method }}
  mount: {{ .Values.defaultAuthMethod.mount }}
  kubernetes:
    role: {{ .Values.defaultAuthMethod.kubernetes.role }}
    serviceAccount: {{ .Values.defaultAuthMethod.kubernetes.serviceAccount }}
    {{- if .Values.defaultAuthMethod.kubernetes.tokenAudiences }}
    audiences: {{ .Values.defaultAuthMethod.kubernetes.tokenAudiences | toJson }}
    {{- end }}
  {{- if .Values.defaultAuthMethod.headers }}
  headers:
    {{ tpl .Values.defaultAuthMethod.headers . | trim }}
  {{- end }}
  {{- if .Values.defaultAuthMethod.params }}
  params:
    {{ tpl .Values.defaultAuthMethod.params . | trim }}
  {{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-pre-delete-vault-auth-cr
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "chart.fullname" . }}-pre-delete-vault-auth-cr
    spec:
      serviceAccountName: {{ include "chart.fullname" . }}-controller-manager
      containers:
      - name: pre-delete-vault-auth
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - {{ printf "kubectl delete vaultauths.secrets.hashicorp.com -n %s default" .Release.Namespace }}
      restartPolicy: Never
{{- end }}
